In [2]:
%timeit [j**4 for j in range (1000000)]# list time

174 ms ± 51.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
import numpy as np
%timeit np.arange(1000000)**4 # numpy time

3.35 ms ± 70.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
# create array in numpy
x=[1,2,3,4,5]
y=np.array(x)
print(y)
print(type(y))# data type of array
print(y.ndim)#dimenstion of array


[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [ ]:
a= np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
# input array from user
l=[]
for i in range(1,5):
  a=int(input("enter choices"))
  l.append(a)
print(np.array(l))

enter choices2
enter choices3
enter choices5
enter choices4
[2 3 5 4]


In [ ]:
ar2=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
2


In [ ]:
ar3=np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]
3


In [6]:
#zero array
ar_zero=np.zeros(4)#array with four elemnt
ar_zero1=np.zeros((3,4))#array with threee rows and four clolumn
print (ar_zero)
print(ar_zero1)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
#ones array
np_one=np.ones((3,4))
print(np_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
# create a empy array
ar_em=np.empty(4)
print(ar_em)

[3.0239794e-315 0.0000000e+000 6.6843255e-310 5.7630663e-317]


In [11]:
#range array
ar_rn=np.arange(4)# make array from zero of 4 len
print(ar_rn)

[0 1 2 3]


In [13]:
#digonal
arr=np.eye(3)# identiy martix of 3x3
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
#linspace
arr=np.linspace(0,10,num=5) #like ap of 5 len and last digit is 10
print(arr)

[ 0.   2.5  5.   7.5 10. ]
