In [5]:
# import libiary
import numpy as np
import time


In [6]:
# test and compare performance of numpy vs plain python loop -vector addtion
n=10000000
a =[1]*n
b=[2]*n
start = time.time()

c=[0]*n
for i in range (n):
    c[i]=a[i]+b[i]
end = time.time()
print(end-start)



1.5090315341949463


In [8]:
#numpy implementation
s =time.time()

a_np=np.arange(n) # numpy array
b_np= np.arange(n)
c_np=a_np+ b_np
e =time.time()
print(e-s)


0.11437082290649414


In [16]:
# create two matrix using numpy array
A = np.array([[1,2,3],[0,1,0],[0,0,1]]) #matric-A
B= np.array([[0,1,0],[1,0,0],[1,2,1]])# matrix B




In [12]:
A.shape

(3, 3)

In [13]:
A

array([[1, 2, 3],
       [0, 1, 0],
       [0, 0, 1]])

In [17]:
# sum of two matrix
print(A+B)

[[1 3 3]
 [1 1 0]
 [1 2 2]]


In [18]:
# MULTIPIUCATION OF TWO MATIX
print(A@B)
print(np.matmul(A,B))


[[5 7 3]
 [1 0 0]
 [1 2 1]]
[[5 7 3]
 [1 0 0]
 [1 2 1]]


In [19]:
# find transpose of matrix
print(A.T)
print(np.transpose(A))


[[1 0 0]
 [2 1 0]
 [3 0 1]]
[[1 0 0]
 [2 1 0]
 [3 0 1]]


In [20]:
# find dt of matrix
print(np.linalg.det(A))


1.0


In [21]:
# inverse of matrix
print(np.linalg.inv(B))


[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [-2. -1.  1.]]


In [22]:
# trace
print(np.linalg.trace(A))


3


In [23]:
#find rank of matrix
print(np.linalg.matrix_rank(A))

3


In [24]:
# eign value and eign vector
print(np.linalg.eig(A))


EigResult(eigenvalues=array([1., 1., 1.]), eigenvectors=array([[ 1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 0.00000000e+00,  1.11022302e-16,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  7.40148683e-17]]))
